#!/bin/bash

set -Eeo pipefail

stack_name=dashboard
tf_dir=terraform
aws_region="eu-west-2"
state_lock_table="prm-gp2gp-terraform-table"
s3_state_key=${stack_name}/terraform.tfstate

function assume_role {
    stack_env=$1
    role_arn=$(
        aws ssm get-parameters \
        --region ${aws_region} \
        --names /registrations/${stack_env}/user-input/cross-account-admin-role \
        --query Parameters[0].Value --output text
    )

    session_name="terraform-registrations-dashboard-${stack_env}"

    echo "Assuming ${stack_env} role..."

    sts=$(
        aws sts assume-role \
        --role-arn $role_arn \
        --role-session-name $session_name
    )

    export AWS_ACCESS_KEY_ID=$(echo $sts | jq -r .Credentials.AccessKeyId)
    export AWS_SECRET_ACCESS_KEY=$(echo $sts | jq -r .Credentials.SecretAccessKey)
    export AWS_SESSION_TOKEN=$(echo $sts | jq -r .Credentials.SessionToken)
}

function tf_init {
    stack_env=$1
    rm -rf .terraform

    state_bucket="prm-gp2gp-terraform-state-${stack_env}"

    terraform init \
        -backend-config key=${s3_state_key} \
        -backend-config bucket=${state_bucket} \
        -backend-config dynamodb_table=${state_lock_table} \
        -backend-config region=${aws_region} \
        ${tf_dir}
}

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 TASK [STACK-ENVIRONMENT]"
    exit 1
fi

task="$1"

echo "--- ${task} ---"
case "${task}" in
    validate)
        stack_env="$2"
        assume_role $stack_env
        tf_init $stack_env
        terraform validate ${tf_dir}
    ;;
    dojo-validate)
        stack_env="$2"
        dojo "./tasks validate ${stack_env}"
    ;;
    plan)
        stack_env="$2"
        assume_role $stack_env
        tf_init $stack_env
        terraform plan \
            -var-file="${stack_env}.tfvars" \
            -out=${stack_env}.tfplan ${tf_dir}
    ;;
    dojo-plan)
        stack_env="$2"
        dojo "./tasks plan ${stack_env}"
    ;;
    apply)
        stack_env="$2"
        assume_role $stack_env
        tf_init $stack_env
        terraform apply ${stack_env}.tfplan
    ;;
    dojo-apply)
        stack_env="$2"
        dojo "./tasks apply ${stack_env}"
    ;;
    format)
        terraform fmt terraform
    ;;
    *)
        echo "Invalid task: '${task}'"
        exit 1
    ;;
esac

set +e
