format_version: 4
pipelines:
  "prm-gp2gp-dashboard-infra":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - NHS_ACCOUNT=common-dev ./tasks dojo-validate
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: common-dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - NHS_ACCOUNT=common-dev ./tasks dojo-plan
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: common-dev.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - NHS_ACCOUNT=common-dev ./tasks dojo-apply
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: common-prod.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - NHS_ACCOUNT=common-prod ./tasks dojo-plan
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: common-prod.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - NHS_ACCOUNT=common-prod ./tasks dojo-apply
